### ISSUE TITLE
[Feature] URL bar or access to url

### ISSUE THREAD

**Issue by HeapUnderfl0w** [kingbri1/Asobi#11]
ok to clobber everything together again that i had from serenity & so on:

i am sorely missing a url bar or some way of:
- grabbing the current url in its entirety (clipboard or a selectable text field)
- browsing to a specific url (url bar or a "go to url" popup)
  - (QoS) a way of seeing history / browsed to urls (as hints while typing an url or as a separate page, related to #5 )

this is due to some sites being indexed on search machines here. this leads to me having to painstakingly find a working link for the page i want to go to, or to make my own horribly looking jump page.

**Comment by kingbri1** [comment]
Can you provide an example for an indexed page? It would be good to take a look and see what I can do. A URL field in history will be added in the next version.

**Comment by HeapUnderfl0w** [comment]
in this case:
https://zoro.to and some similar streaming services

(also indexed in this case means that they do not appear in search results. this is specifically prevalent in google, but pages like duckduckgo are not free from it)

**Comment by kingbri1** [comment]
Resolved in fa1e90afbb1ba1083f7ba1c09ff5158d04284cd6
