### ISSUE TITLE
[Feature request] Add option to have the bottom bar auto hide

### ISSUE THREAD

**Issue by alven-shin** [kingbri1/Asobi#12]
Triple tapping to hide is a bit of a pain., so it would be cool for the bottom bar with the navi controls to auto-hide after a specified amount of time. Same for the top bar if that ever gets added too. The time could be specified in the settings or auto-hide could be disabled too. Oh and hide on scroll would be another option too.

**Comment by kingbri1** [comment]
- Auto hide: Good idea, will be another settings option in a future version.
- Hide on scroll: This can be a bit jarring and requires some work to put in. Not sure if I will implement this, but if I do, it'll be in a future version.
